name: Cypress Tests on Chrome using Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-cypress-tests .

      - name: Start server and wait for it to be available
        run: |
          npm install
          npm start &
          npx wait-on http://localhost:8080

      - name: Run Cypress tests in Chrome using Docker
        run: docker run --rm my-cypress-tests

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
